spring:
  application:
    name: hh-week2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:

  # JPA
  jpa:
    hibernate:
      ddl-auto: create